name: wi
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`.
publish_to: "none"

# android build command: flutter build appbundle --target-platform android-arm,android-arm64
# ios build command: flutter build ios
version: 1.0.1+101001

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_advertising_id: ^1.0.2
  intl: ^0.16.0
  dio: ^3.0.10
  http: ^0.12.0+2
  rxdart: ^0.24.1
  hive: ^1.4.1
  hive_flutter: ^0.3.0+2
  connectivity: ^0.4.9
  permission_handler: ^5.0.1+1
  app_settings: ^4.0.2
  google_fonts: ^1.1.0
  flutter_svg: ^0.19.3
  path_provider: ^1.5.1
  json_annotation: ^3.0.1
  url_launcher: ^5.4.1
  get_it: ^4.0.2
  image_picker: ^0.6.7+3
  file_picker: ^1.13.0+1
  firebase_core: ^0.7.0
  firebase_analytics: ^7.0.1
  firebase_auth: ^0.20.0+1
  firebase_messaging: ^8.0.0-dev.14
  cloud_firestore: ^0.16.0
  firebase_storage: ^7.0.0
  firebase_remote_config: ^0.6.0
  google_sign_in: ^4.5.1
  slider_button: ^0.5.0
  camera: ^0.8.0
  photo_view: ^0.9.2
  image: ^2.1.18
  image_size_getter: ^0.1.1
  sticky_grouped_list: ^0.3.0
  flutter_cache_manager_firebase: ^1.0.0
  flutter_image_compress: ^0.7.0
  video_compress: ^2.1.1
  video_player: ^0.10.12+2
  responsive_util: ^0.3.0
  visibility_detector: ^0.1.5
  supercharged: ^1.10.0
  # workmanager:
  #   git:
  #     url: https://github.com/ened/flutter_workmanager.git
  #     ref: 1c4e162ea4e71855856fb9e55a1545b3dae9a25d # Temp Flutter 1.20 compatibility. You, from the future, please check the plugin updates and revert to pulling from Pub if a fix has been released.
  geolocator: ^6.0.0+4
  share: ^0.6.5+2
  admob_flutter: ^1.0.1
  sign_in_with_apple: ^2.5.4
  shimmer: ^1.1.2
  flutter_facebook_login: ^3.0.0
  photofilters: ^2.0.1
  image_cropper: ^1.3.1
  shared_preferences: ^0.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  analyzer: 0.39.14
  build_runner: ^1.7.2
  json_serializable: ^3.5.0
  hive_generator: ^0.8.1

dependency_overrides:
  analyzer: 0.40.4
  quiver: ^2.1.3
  firebase_storage: ^7.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
