name: wi
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`.
publish_to: "none"

version: 0.0.0+001001

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.16.0
  dio: ^3.0.8
  http: ^0.12.0+2
  rxdart: ^0.24.1
  hive: ^1.4.1
  hive_flutter: ^0.3.0+2
  google_fonts: ^1.1.0
  flutter_svg: ^0.17.4
  path_provider: ^1.5.1
  json_annotation: ^3.0.1
  url_launcher: ^5.4.1
  get_it: ^4.0.2
  sup: ^1.0.1
  image_picker: ^0.6.7+3
  firebase_core: ^0.4.0+9
  firebase_analytics: ^5.0.2
  firebase_auth: ^0.14.0+5
  cloud_firestore: ^0.12.9+5
  firebase_storage: ^3.1.6
  flutter_auth_buttons: ^0.8.0
  google_sign_in: ^4.5.1
  slider_button: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.2
  json_serializable: ^3.2.5
  hive_generator: ^0.7.0

dependency_overrides:
  quiver: ^2.1.3

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
